name: nyc_taxi_dbt
version: '1.0.0'
profile: nyc_taxi_dbt

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  nyc_taxi_dbt:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    dimensions:
      +materialized: table
    facts:
      +materialized: incremental
    marts:
      +materialized: table